language: php

php:
  - 5.6
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - wget https://phar.phpunit.de/phpunit-5.phar
  - chmod 777 ./phpunit.phar
  - chmod 777 ./phpunit-5.phar

script:
  - if [ $(phpenv version-name) = "5.6" ]; then ./phpunit-5.phar; else ./phpunit.phar; fi
